apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-lizu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ubjc-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-lizu@sha256:5be34c2c99d10652e90f0be49eb7cb7aff96d2ce01d2f55b282943ca15439499
        name: my-python
        resources: {}
status: {}
