apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-lizu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-docker-python-rhtap-three-component-scenarios-lizu
    app.kubernetes.io/part-of: mc-three-scenarios
  name: devfile-docker-python-rhtap-three-component-scenarios-lizu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-lizu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-docker-python-rhtap-three-component-scenarios-lizu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ubjc-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-lizu@sha256:5be34c2c99d10652e90f0be49eb7cb7aff96d2ce01d2f55b282943ca15439499
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
